# -*- coding: utf-8 -*-
"""Another_copy_of_crop_detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Varshu006/Travel-the-world/blob/main/Another_copy_of_crop_detector.ipynb
"""



import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

# Check karne ke liye ki sab sahi hai
print("Setup Complete!")

dataset_path = 'Tomato'
img_size=(224,224)
batch_size=32

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=20,
    horizontal_flip=True
)

train_gen = datagen.flow_from_directory(
    dataset_path,
    target_size=img_size,
    batch_size=batch_size,
    subset='training'
)

val_gen = datagen.flow_from_directory(
    dataset_path,
    target_size=img_size,
    batch_size=batch_size,
    class_mode='categorical',
    subset='validation'
)

base_model=MobileNetV2(weights='imagenet',
                       include_top=False,
                       input_shape=(224,224,3))

base_model.trainable=False

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128,activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(train_gen.num_classes,activation='softmax')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

print("training shuru ho rhi h....")
history = model.fit(train_gen,
                    validation_data=val_gen, epochs=10)

model.save('tomato_diseases_model.h5')
print("Model save ho gya:tomato_disease_model.h5")

print("Classes mapping:",train_gen.class_indices)

import numpy as np
from tensorflow.keras.preprocessing import image

def predict_and_advise(img_path):
    # 1. Image ko load aur prepare karna
    img = image.load_img(img_path, target_size=(224, 224))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0) / 255.0

    # 2. Prediction lena
    predictions = model.predict(img_array)
    class_idx = np.argmax(predictions)

    # 3. Mapping aur Advisory Dictionary
    classes = {0: 'Bacterial spot', 1: 'Early blight', 2: 'Late blight', 3: 'Leaf Mold',
               4: 'Septoria leaf spot', 5: 'Spider mites', 6: 'Target Spot',
               7: 'Yellow Leaf Curl Virus', 8: 'Mosaic virus', 9: 'Healthy'}

    advisories = {
        'Bacterial spot': 'Advisory: Copper-based spray use karein aur khet mein hygiene rakhein.',
        'Early blight': 'Advisory: Purani pattiyan hata dein aur Fungicide ka spray karein.',
        'Late blight': 'Advisory: Fasal ko dry rakhein. Ye tezi se failta hai, turant treatment shuru karein.',
        'Leaf Mold': 'Advisory: Hawa ka flow (ventilation) badhayein aur humidity kam karein.',
        'Septoria leaf spot': 'Advisory: Potassium rich fertilizer dein aur pani pattiyon par na gire.',
        'Spider mites': 'Advisory: Insecticidal soap ya Neem oil ka use karein.',
        'Target Spot': 'Advisory: Plants ke beech gap rakhein taaki sunlight andar tak jaye.',
        'Yellow Leaf Curl Virus': 'Advisory: Iska koi ilaj nahi hai. Safed makkhi (Whiteflies) ko rokne ke liye jaal lagayein.',
        'Mosaic virus': 'Advisory: Infected plants ko turant nikal kar jala dein taaki virus na faile.',
        'Healthy': 'Advisory: Aapki fasal mast hai! Bas regular monitoring karte rahein.'
    }

    result = classes[class_idx]
    print(f"Detected Disease: {result}")
    print(advisories[result])

# Test karne ke liye (Kisi photo ka path yahan likhein):
# predict_and_advise('test_image.jpg')

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print(f'user ne file"{fn} upload ki....')
  predict_and_advise(fn)